version: "3.4"
services:
  alertmanager:
    build:
      context: ./alertmanager
    image: alertmanager:latest
    volumes:
      - alertmanager-data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    restart: ${RESTART}
    ports:
      - '${ALERTMANAGER_PORT}:9093'
    expose:
      - ${ALERTMANAGER_PORT}/tcp
    depends_on:
      - prometheus
    
  eth2:
    depends_on:
      - alertmanager

volumes:
  alertmanager-data:
