version: "3.4"

services:
  heimdall:
    image: "maticnetwork/heimdall:${HEIMDALL_TAG}"
#    stop_grace_period: 3m
    command: >
      bash -c "
        if [ ! -f \"/root/.heimdalld/config/config.toml\" ]
        then
          heimdalld init --home /root/.heimdalld --chain-id ${HEIMDALL_CHAIN_ID}
          wget -O /root/snapshot/heimsnap.tgz ${HEIMDALL_SNAPSHOT_FILE}
          tar -xzvf /root/snapshot/heimsnap.tgz -C /root/.heimdalld/data/
          rm /root/snapshot/heimsnap.tgz
        fi \
        && wget -O /root/.heimdalld/config/genesis.json ${HEIMDALL_GENESIS_URL} -P /root/.heimdalld/config \
        && sed -i '/seeds =/c\seeds = \"${HEIMDALL_SEEDS}\"' /root/.heimdalld/config/config.toml \
        && sed -i '/26657/c\laddr = \"tcp://0.0.0.0:26657\"' /root/.heimdalld/config/config.toml \
        && sed -i '/bor_rpc_url/c\bor_rpc_url = \"${HEIMDALL_BOR_RPC_URL}\"' /root/.heimdalld/config/heimdall-config.toml \
        && sed -i '/eth_rpc_url/c\eth_rpc_url = \"${HEIMDALL_ETH_RPC_URL}\"' /root/.heimdalld/config/heimdall-config.toml \
        && wget -O /root/scripts/heimdall-startup.sh ${HEIMDALL_START} \
        && cd /root/scripts && sh ./heimdall-startup.sh && sleep infinity
      "
    volumes:
      - heimdall-scripts:/root/scripts
      - heimdall-snapshot:/root/snapshot
      - heimdall-logs:/root/logs/
      - heimdall-data:/root/.heimdalld
    expose:
      - "1317/tcp"
      - "26657/tcp"
    ports:
      - "26656:26656"

  bor:
    image: "maticnetwork/bor:${BOR_TAG}"
    stop_grace_period: 3m
    command: >
      sh -c "
        set -x \
        && if [ ! -f \"/root/.bor/setupdone\" ]
        then
          cd /root/
          wget -O setup.sh ${BOR_SETUP}
          sed -i '/^cp .\/static-nodes.json/d' setup.sh
          wget -O genesis.json ${BOR_GENESIS}
          sh setup.sh
          mkdir -p /root/.bor/snapshot
          if [ ${BOR_MODE} == \"archive\" ]
          then
            wget -O /root/.bor/snapshot/borsnap.tgz ${BOR_ARCHIVE_NODE_SNAPSHOT_FILE}
          else
            wget -O /root/.bor/snapshot/borsnap.tgz ${BOR_FULL_NODE_SNAPSHOT_FILE}
          fi
          tar -xzvf /root/.bor/snapshot/borsnap.tgz -C /root/.bor/data/bor/chaindata
          rm /root/.bor/snapshot/borsnap.tgz
          touch /root/.bor/setupdone
        fi \
        && exec bor --datadir /root/.bor/data \
        --gcmode ${BOR_MODE} \
        --ws --ws.port 8546 --ws.addr 0.0.0.0 --ws.origins \"*\" \
        --port ${BOR_P2P_PORT} \
        --txpool.locals ${TX_LOCAL_ADDR} \
        --txpool.globalslots \"100000\" \
        --rpc.txfeecap \"0\" \
        --txpool.accountslots \"128\" \
        --bor.heimdall http://heimdall:1317 \
        --bootnodes \"enode://0cb82b395094ee4a2915e9714894627de9ed8498fb881cec6db7c65e8b9a5bd7f2f25cc84e71e89d0947e51c76e85d0847de848c7782b13c0255247a6758178c@44.232.55.71:30303,enode://88116f4295f5a31538ae409e4d44ad40d22e44ee9342869e7d68bdec55b0f83c1530355ce8b41fbec0928a7d75a5745d528450d30aec92066ab6ba1ee351d710@159.203.9.164:30303\" \
        --syncmode \"full\" \
        --txpool.accountqueue 64 \
        --txpool.globalqueue 131072 \
        --maxpeers 200 \
        --ipcdisable \
        --http --http.addr \"0.0.0.0\" --http.vhosts \"*\" \
        --http.api \"eth,net,web3,txpool,bor\" \
        --http.port 8545
      "
    volumes:
      - bor-data:/root/.bor
    expose:
      - "8545/tcp"
      - "8546/tcp"
    ports:
      - ${BOR_P2P_PORT}:${BOR_P2P_PORT}/tcp
      - ${BOR_P2P_PORT}:${BOR_P2P_PORT}/udp

  eth:
    depends_on:
      - heimdall
      - bor

volumes:
  bor-data:
  heimdall-scripts:
  heimdall-snapshot:
  heimdall-logs:
  heimdall-data:
