version: "3.4"
services:
  deposit-cli-new:
    restart: "no"
    build:
      context: ./eth2.0-deposit-cli
      args:
        - BUILD_TARGET=${DEPCLI_SRC_BUILD_TARGET}
    image: eth2.0-deposit-cli:local
    volumes:
      - ${DEPCLI_LOCALDIR}:/app/.eth2/
    entrypoint:
      - docker-entrypoint.sh
      - python3
      - /app/eth2deposit/deposit.py
      - new-mnemonic
      - --chain
      - ${NETWORK}
  deposit-cli-existing:
    restart: "no"
    image: eth2.0-deposit-cli:local
    volumes:
      - ${DEPCLI_LOCALDIR}:/app/.eth2/
    entrypoint:
      - docker-entrypoint.sh
      - python3
      - /app/eth2deposit/deposit.py
      - existing-mnemonic
      - --chain
      - ${NETWORK}
