version: "3"
services:
  geth:
    restart: "on-failure"
    user: ${GETH_UID}:${GETH_UID}      
    build:
      context: ./geth
      args:
        - BUILD_TARGET=${GETH_BUILD_TARGET} 
        - USER=${GETH_USER}
        - UID=${GETH_UID}
    image: geth
    volumes:
      - geth-data:/var/lib/goethereum
    ports:
      - ${GETH_PORT}:30303/tcp
      - ${GETH_PORT}:30303/udp
    entrypoint: ${GETH_ENTRYPOINT}
    command:
      - ${ETH_NETWORK}
  lh-beacon:
    restart: "on-failure"
    user: ${LH_UID}:${LH_UID}
    build:
      context: ./lighthouse
      args:
        - BUILD_TARGET=${LH_BUILD_TARGET}
        - USER=${LH_USER}
        - UID=${LH_UID}
    image: lighthouse
    volumes:
      - lhbeacon-data:/var/lib/lighthouse
    ports:
      - ${LH_PORT}:9000/tcp
      - ${LH_PORT}:9000/udp
    entrypoint: ${LH_ENTRYPOINT}
    command:
      - --testnet
      - ${LH_TESTNET}
      - --eth1-endpoint
      - ${LH_ETH1_NODE}
  lh-validator:
    restart: "on-failure"
    user: ${LH_UID}:${LH_UID}
    build:
      context: ./lighthouse
      args:
        - BUILD_TARGET=${LH_BUILD_TARGET}
        - USER=${LH_USER}
        - UID=${LH_UID}
    image: lighthouse
    volumes:
      - ./.eth2/lighthousevalidator-data:/var/lib/lighthouse
    entrypoint: ["lighthouse", "--datadir", "/var/lib/lighthouse"]
    command: ["validator", "--server", "http://lh-beacon:5052"]
  prysm-beacon:
    restart: "on-failure"
    user: ${PRYSM_UID}:${PRYSM_UID}
    build:
      context: ./prysm
      args:
        - BUILD_TARGET=${PRYSM_BUILD_TARGET}
        - USER=${PRYSM_USER}
        - UID=${PRYSM_UID}
    image: prysm
    volumes:
      - prysmbeacon-data:/var/lib/prysm
    ports:
      - ${PRYSM_PORT}:13000/tcp
      - ${PRYSM_UDP_PORT}:12000/udp
    entrypoint: ${PRYSM_ENTRYPOINT}
    command:
      - --http-web3provider
      - ${PRYSM_ETH1_NODE}
  prysm-validator:
    restart: "on-failure"
    user: ${PRYSM_UID}:${PRYSM_UID}
    build:
      context: ./prysm
      args:
        - BUILD_TARGET=${PRYSM_BUILD_TARGET}
        - USER=${PRYSM_USER}
        - UID=${PRYSM_UID}
    image: prysm
    volumes:
      - ./.eth2/prysmvalidator-data:/var/lib/prysm
    entrypoint: ["validator", "--datadir", "/var/lib/prysm", "--wallet-dir", "/var/lib/prysm/prysm-wallet"]
    command: ["--beacon-rpc-provider", "http://prysm-beacon:4000"]
  lighthouse:
    image: tianon/true
    restart: "no"
    depends_on:
      - geth
      - lh-beacon
      - lh-validator
  prysm:
    image: tianon/true
    restart: "no"
    depends_on:
      - geth
      - prysm-beacon
      - prysm-validator
volumes:
  geth-data:
  lhbeacon-data:
  prysmbeacon-data:
