version: "3.4"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  execution:
    restart: "${RESTART}"
    build:
      context: ./erigon
      dockerfile: ${ERIGON_DOCKERFILE}
      args:
        - BUILD_TARGET=${ERIGON_SRC_BUILD_TARGET}
        - DOCKER_TAG=${ERIGON_DOCKER_TAG}
    stop_grace_period: 5m
    image: erigon:merge
# Root so a chown can happen for the secret, then su-exec into erigon. This can become erigon again
# after merge
    user: root
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - OVERRIDE_TTD=${OVERRIDE_TTD}
      - LOG_LEVEL=${LOG_LEVEL}
    volumes:
      - erigon-el-data:/var/lib/erigon
      - /etc/localtime:/etc/localtime:ro
      - jwtsecret:/var/lib/erigon/secrets
    ports:
      - ${EL_P2P_PORT-30303}:${EL_P2P_PORT:-30303}/tcp
      - ${EL_P2P_PORT-30303}:${EL_P2P_PORT:-30303}/udp
      # torrent ports
      - ${ERIGON_TORRENT_PORT:-42069}:${ERIGON_TORRENT_PORT:-42069}/tcp
      - ${ERIGON_TORRENT_PORT:-42069}:${ERIGON_TORRENT_PORT:-42069}/udp
    networks:
      default:
        aliases:
          - eth1
    <<: *logging
    entrypoint:
      - docker-entrypoint.sh
      - erigon
      - --private.api.addr
      - 0.0.0.0:9090
      - --datadir
      - /var/lib/erigon
      - --port
      - ${EL_P2P_PORT:-30303}
      - --torrent.port
      - ${ERIGON_TORRENT_PORT:-42069}
      - --nat
      - any
      - --chain
      - ${NETWORK}
      - --prune=htc
      - --metrics
      - --metrics.addr
      - 0.0.0.0
      - --metrics.expensive
      - --http
      - --http.addr
      - 0.0.0.0
      - --http.port
      - ${EL_RPC_PORT}
      - --http.vhosts=*
      - --http.corsdomain=*
      - --http.api
      - web3,eth,net,engine
      - --ws
      - --engine.addr
      - 0.0.0.0
      - --engine.port
      - "8551"
      - --authrpc.jwtsecret
      - /var/lib/erigon/secrets/jwtsecret
      # Workaround for high memory use in alpha
      - --batchSize
      - 128m
volumes:
  erigon-el-data:
  jwtsecret:
