version: "3.9"
services:
  ethdo:
    profiles: ["tools"]
    restart: "no"
    image: wealdtech/ethdo:latest
    entrypoint:
      - /app/ethdo
      -  --connection
      - http://consensus:5052
      - --allow-insecure-connections
