version: "3"
services:
  geth:
    restart: "${RESTART}"
    user: ${LOCAL_UID}:${LOCAL_UID}
    build:
      context: ./geth
      args:
        - BUILD_TARGET=${GETH_BUILD_TARGET} 
        - USER=${GETH_USER}
        - UID=${LOCAL_UID}
    image: geth
    volumes:
      - geth-data:/var/lib/goethereum
    ports:
      - ${GETH_PORT}:${GETH_PORT}/tcp
      - ${GETH_PORT}:${GETH_PORT}/udp
    expose:
      - 8545
    entrypoint:
      - geth
      - --nousb
      - --http
      - --http.addr
      - 0.0.0.0
      - --http.vhosts=*
      - --http.api
      - eth,net
      - --ipcdisable
      - --datadir
      - /var/lib/goethereum
      - --${ETH_NETWORK}
      - --port
      - ${GETH_PORT}
  beacon:
    depends_on:
      - geth
  eth2:
    depends_on:
      - geth
volumes:
  geth-data:
