version: "3.4"
services:
  eth1:
    restart: "${RESTART}"
    build:
      context: ./geth
      dockerfile: ${GETH_DOCKERFILE}
      args:
        - BUILD_TARGET=${GETH_SRC_BUILD_TARGET} 
        - DOCKER_TAG=${GETH_DOCKER_TAG}
    stop_signal: SIGINT
    stop_grace_period: 3m
    image: geth:local
    volumes:
      - geth-eth1-data:/var/lib/goethereum
    ports:
      - ${ETH1_PORT}:${ETH1_PORT}/tcp
      - ${ETH1_PORT}:${ETH1_PORT}/udp
    expose:
      - ${ETH1_RPC_PORT}/tcp
      - ${ETH1_WS_PORT}/tcp
    entrypoint:
      - docker-entrypoint.sh
      - geth
      - --http
      - --http.addr
      - 0.0.0.0
      - --http.vhosts=*
      - --http.api
      - web3,eth,net
      - --datadir
      - /var/lib/goethereum
      - --port
      - ${ETH1_PORT}
      - --http.port
      - ${ETH1_RPC_PORT}
      - --ws
      - --ws.addr
      - 0.0.0.0
      - --ws.port
      - ${ETH1_WS_PORT}
      - --ws.api
      - web3,eth,net
      - --${ETH1_NETWORK}
  eth2:
    depends_on:
      - eth1
volumes:
  geth-eth1-data:
