# To be used in conjunction with heco.yml
version: "3.4"
services:
  execution:
    labels:
      - traefik.enable=true
      - traefik.http.routers.heco.service=heco
      - traefik.http.routers.heco.entrypoints=websecure
      - traefik.http.routers.heco.rule=Host(`${EC_HOST}.${DOMAIN}`)
      - traefik.http.services.heco.loadbalancer.server.port=${EC_RPC_PORT}
      - traefik.http.routers.hecows.service=hecows
      - traefik.http.routers.hecows.entrypoints=websecure
      - traefik.http.routers.hecows.rule=Host(`${EC_WS_HOST}.${DOMAIN}`)
      - traefik.http.services.hecows.loadbalancer.server.port=${EC_WS_PORT}

  eth:
    image: tianon/true
