version: "3.4"
services:
  heco:
    restart: "${RESTART}"
    build:
      context: ./geth
      dockerfile: Dockerfile.heco
      args:
        - BUILD_TARGET=${GETH_SRC_BUILD_TARGET}
    stop_grace_period: 3m
    image: heco:local
    volumes:
      - heco-ec-data:/data/heco/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 32668:32668/tcp
      - 32668:32668/udp
    expose:
      - 8545/tcp
      - 8546/tcp
    entrypoint:
      - geth
      - --config
      - /data/heco/data/config.toml
      #- --ws.origins="*"
  eth:
    depends_on:
      - heco
volumes:
  heco-ec-data:
