version: "3.4"
services:
  heco:
    restart: "${RESTART}"
    build:
      context: ./geth
      dockerfile: Dockerfile.heco
      args:
        - BUILD_TARGET=${GETH_SRC_BUILD_TARGET}
    stop_grace_period: 3m
    image: heco:local
    volumes:
      - heco-ec-data:/data/heco/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 32668:32668/tcp
      - 32668:32668/udp
    expose:
      - 8545/tcp
      - 8546/tcp
    entrypoint:
      - geth
      - --config
      - /data/heco/data/config.toml
      #- --ws.origins="*"
    labels:
      - traefik.enable=true
      - traefik.http.routers.heco.service=heco
      - traefik.http.routers.heco.entrypoints=websecure
      - traefik.http.routers.heco.rule=Host(`${EC_HOST}.${DOMAIN}`)
      - traefik.http.services.heco.loadbalancer.server.port=8545
      - traefik.http.routers.hecows.service=hecows
      - traefik.http.routers.hecows.entrypoints=websecure
      - traefik.http.routers.hecows.rule=Host(`${EC_WS_HOST}.${DOMAIN}`)
      - traefik.http.services.hecows.loadbalancer.server.port=8546

  eth:
    image: tianon/true
    depends_on:
      - heco

volumes:
  heco-ec-data:
