version: "3"
services:
  beacon:
    restart: "no"
    user: ${LOCAL_UID}:${LOCAL_UID}
    build:
      context: ./lighthouse
      args:
        - BUILD_TARGET=${LH_BUILD_TARGET}
        - USER=${LH_USER}
        - UID=${LOCAL_UID}
    image: lighthouse
    volumes:
      - lhbeacon-data:/var/lib/lighthouse
    ports:
      - ${LH_PORT}:${LH_PORT}/tcp
      - ${LH_PORT}:${LH_PORT}/udp
    expose:
      - 5052/tcp
    entrypoint: 
      - lighthouse
      - bn
      - --datadir
      - /var/lib/lighthouse
      - --http
      - --http-address
      - 0.0.0.0
      - --testnet
      - ${TESTNET}
      - --port
      - ${LH_PORT}
      - --eth1-endpoint
      - ${ETH1_NODE}
      - --debug-level=${LOG_LEVEL}
  validator:
    restart: "no"
    user: ${LOCAL_UID}:${LOCAL_UID}
    build:
      context: ./lighthouse
      args:
        - BUILD_TARGET=${LH_BUILD_TARGET}
        - USER=${LH_USER}
        - UID=${LOCAL_UID}
    image: lighthouse
    volumes:
      - lhvalidator-data:/var/lib/lighthouse
    entrypoint:
      - lighthouse
      - validator
      - --datadir
      - /var/lib/lighthouse
      - --beacon-node
      - http://beacon:5052
      - --graffiti
      - ${GRAFFITI}
      - --testnet
      - ${TESTNET}
      - --debug-level=${LOG_LEVEL}
    depends_on:
      - beacon
  validator-import:
    restart: "no"
    user: ${LOCAL_UID}:${LOCAL_UID}
    image: lighthouse
    build:
      context: ./lighthouse
      args:
        - BUILD_TARGET=${LH_BUILD_TARGET}
        - USER=${LH_USER}
        - UID=${LOCAL_UID}
    volumes:
      - lhvalidator-data:/var/lib/lighthouse
      - ${DEPCLI_LOCALDIR}/validator_keys:/var/lib/lighthouse/validator_keys
    entrypoint:
      - query-lh-validator-passwords.sh
      - lighthouse
      - account
      - validator
      - import
      - --datadir
      - /var/lib/lighthouse
      - --directory
      - /var/lib/lighthouse/validator_keys
      - --testnet
      - ${TESTNET}
      - --debug-level=${LOG_LEVEL}
  deposit-cli:
    restart: "no"
    user: ${LOCAL_UID}:${LOCAL_UID}
    build:
      context: ./eth2.0-deposit-cli
      args:
        - BUILD_TARGET=${DEPCLI_BUILD_TARGET}
        - USER=${DEPCLI_USER}
        - UID=${LOCAL_UID}
    image: eth2.0-deposit-cli
    volumes:
      - ${DEPCLI_LOCALDIR}:/var/lib/depcli-data
    entrypoint: ${DEPCLI_ENTRYPOINT}
    command:
      - --num_validators
      - ${NUMVAL}
      - --chain
      - ${TESTNET}
  eth2:
    image: tianon/true
    restart: "no"
    depends_on:
      - beacon
      - validator
volumes:
  lhbeacon-data:
  lhvalidator-data:
