version: "3.4"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  consensus:
    restart: "unless-stopped"
    build:
      context: ./lodestar
      dockerfile: ${LS_DOCKERFILE}
      args:
        - BUILD_TARGET=${LS_SRC_BUILD_TARGET}
        - DOCKER_TAG=${LS_DOCKER_TAG}
    image: lodestar:merge
    user: lsconsensus
    stop_grace_period: 1m
    volumes:
      - lsconsensus-data:/var/lib/lodestar/consensus
      - /etc/localtime:/etc/localtime:ro
      - jwtsecret:/var/lib/lodestar/consensus/ee-secret
    environment:
      - RAPID_SYNC_URL=${RAPID_SYNC_URL}
      - JWT_SECRET=${JWT_SECRET}
      - OVERRIDE_TTD=${OVERRIDE_TTD}
      - MEV_BOOST=${MEV_BOOST}
    ports:
      - ${CL_P2P_PORT:-9000}:${CL_P2P_PORT:-9000}/tcp
      - ${CL_P2P_PORT:-9000}:${CL_P2P_PORT:-9000}/udp
    <<: *logging
    entrypoint:
      - docker-entrypoint.sh
      - node
      - --max-old-space-size=4096
      - /usr/app/node_modules/.bin/lodestar
      - beacon
      - --rootDir
      - /var/lib/lodestar/consensus
      - --api.rest.enabled
      - "true"
      - --api.rest.host
      - 0.0.0.0
      - --api.rest.port
      - ${CL_REST_PORT:-5052}
      - --network.discv5.bindAddr
      - "/ip4/0.0.0.0/udp/${CL_P2P_PORT:-9000}"
      - --network.localMultiaddrs
      - "/ip4/0.0.0.0/tcp/${CL_P2P_PORT:-9000}"
      - --execution.urls
      - ${EL_NODE}
      - --jwt-secret
      - /var/lib/lodestar/consensus/ee-secret/jwtsecret
      - --network.maxPeers
      - ${CL_MAX_PEER_COUNT:-55}
      - --network.targetPeers
      - ${CL_MIN_PEER_COUNT:-50}
      - --logLevel
      - ${LOG_LEVEL}
      - --preset=gnosis
      - --paramsFile=/usr/config.yaml
      - --genesisStateFile=/usr/genesis.ssz
      - --network.discv5.bootEnrs=enr:-Ly4QBWdgA_Tt59pz3xeeMEIv9RXKjJn5pC4TiFxxmGcNrRAUTB5qVs6xTph7SLtLOPxlgn60mxaNyeAHc0inv1Zq40Bh2F0dG5ldHOIAAAAAAAAAACEZXRoMpD1_S08AQAAb1oAAAAAAAAAgmlkgnY0gmlwhJ_LJMCJc2VjcDI1NmsxoQJW6aQs89Fzox8_YwwO1C-ubid5awCWhd8oUPP8s2VepYhzeW5jbmV0cwCDdGNwgiMog3VkcIIjKA
      - --network.discv5.bootEnrs=enr:-Ly4QLtEwF2plyYK6wINg8p2cEvON5uxBRTGDjOVY-alCgBzfYoNqzAnYtMTRbH5iZgXAxAweh90i9FEtbN2OvhKZcMBh2F0dG5ldHOIAAAAAAAAAACEZXRoMpD1_S08AQAAb1oAAAAAAAAAgmlkgnY0gmlwhJ_LJ0qJc2VjcDI1NmsxoQLYBUr39uZ3zPfC9XK0f-g22J2Z8DF1Ax3e444dwUmy0ohzeW5jbmV0cwCDdGNwgiMog3VkcIIjKA
      - --network.discv5.bootEnrs=enr:-Ly4QHyiqcUzJ4CtI6bhSTAZAD92UMEKwKCObZ-9hSZJAfgtXkj4JbAbhK33rXhqLFeO3isINvpPy_TUvoLB71__rOEBh2F0dG5ldHOIAAAAAAAAAACEZXRoMpD1_S08AQAAb1oAAAAAAAAAgmlkgnY0gmlwhJ_fJsSJc2VjcDI1NmsxoQJjSw3xd3o7Rj1DzE7Wxlr6mEbt5s2re4ANlP_TMDLmUohzeW5jbmV0cwCDdGNwgiMog3VkcIIjKA
      - --network.discv5.bootEnrs=enr:-Ly4QN9Ro8-E9gyCCUuEYWlSwCbfzc2NkUGmN8YRDmg4K3rRP1FBiaDe9TWKVGaXhmb8F6qwYxW5h83hS6LjF8nJK34Bh2F0dG5ldHOIAAAAAAAAAACEZXRoMpD1_S08AQAAb1oAAAAAAAAAgmlkgnY0gmlwhJ_fM6-Jc2VjcDI1NmsxoQNEtFv9oWxfpqPxFgpngTaWPHuGC6XEwaLdANypSZ-S2YhzeW5jbmV0cwCDdGNwgiMog3VkcIIjKA
      - --network.discv5.bootEnrs=enr:-Ly4QMpHRs1843yWgB5yA2epcTBo4BrGrEB6b2fPAfxryjEEFzIUc_FOJ3b7r6h0bD_Gg-gCrX_mUgZZM8D7Xfot9J8Bh2F0dG5ldHOIAAAAAAAAAACEZXRoMpD1_S08AQAAb1oAAAAAAAAAgmlkgnY0gmlwhLymbsOJc2VjcDI1NmsxoQKhmKRn59_w2tt_KNQ2Jhj-F3b9hxRkFYdtW3IGgXm0oIhzeW5jbmV0cwCDdGNwgiMog3VkcIIjKA
      - --network.discv5.bootEnrs=enr:-Ly4QO80ytPwEEXF0B6Nsnk6N-89SI3Ja-wvhnMwTgvAiKCMNvOfHwf3FbJtLvZpP7O2v4ztnpqbdYEXngvLzgDsvSEBh2F0dG5ldHOIAAAAAAAAAACEZXRoMpD1_S08AQAAb1oAAAAAAAAAgmlkgnY0gmlwhI5dgFeJc2VjcDI1NmsxoQMwMSfNp9AUZNAgWzYDo2nI1KNHej3aB2NWt8j9awAlO4hzeW5jbmV0cwCDdGNwgiMog3VkcIIjKA
      - --network.discv5.bootEnrs=enr:-Ly4QAnBhPYD4_Cc3CyJhVqkLquWeGIY5xlKLhy9j_Bx845iNwSORtcXdLReWlK33PfqHTbqpsI-rm--egamtkrB7ywBh2F0dG5ldHOIAAAAAAAAAACEZXRoMpD1_S08AQAAb1oAAAAAAAAAgmlkgnY0gmlwhJO20mGJc2VjcDI1NmsxoQLhk56jmgLZTFopIhjoDlWpPiDjzLsrbnX7Z9iaOeg3PIhzeW5jbmV0cwCDdGNwgiMog3VkcIIjKA
      - --network.discv5.bootEnrs=enr:-Ly4QNrYdrX4KY4tPgQKG3KcGySPE7QtpfFCGSujQUpQkErELFeDjuVWRzMxyyEQJTyVlTSPXxy4t9T2yrl4lBf5x8ABh2F0dG5ldHOIAAAAAAAAAACEZXRoMpD1_S08AQAAb1oAAAAAAAAAgmlkgnY0gmlwhI5dxlqJc2VjcDI1NmsxoQIzft6l-G1eo45O7v1eg0AZx4G-uwi4oGARFYQk1_vy5ohzeW5jbmV0cwCDdGNwgiMog3VkcIIjKA
      - --network.discv5.bootEnrs=enr:-Ly4QEGDwovw841Etzs5wJquRZFMGPNNcKh6rqa5_BCI64NKYKOFjWTPh0nbwDBR7caIqEoDMKWBFzTTmqFKIQzjPpsBh2F0dG5ldHOIAAAAAAAAAACEZXRoMpD1_S08AQAAb1oAAAAAAAAAgmlkgnY0gmlwhI5dfvaJc2VjcDI1NmsxoQLTtR9MTMMQxDXWi7Gn3ABZD-NMyIaq1HxUtcDrjM7qz4hzeW5jbmV0cwCDdGNwgiMog3VkcIIjKA
      - --chain.defaultFeeRecipient
      - ${FEE_RECIPIENT}

  validator:
    restart: "unless-stopped"
    image: lodestar:merge
    user: lsvalidator
    environment:
      - MEV_BOOST=${MEV_BOOST}
      - DOPPELGANGER=${DOPPELGANGER}
    volumes:
      - lsvalidator-data:/var/lib/lodestar/validators
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - consensus
    <<: *logging
    entrypoint:
      - docker-entrypoint-vc.sh
      - node
      - --max-old-space-size=4096
      - /usr/app/node_modules/.bin/lodestar
      - validator
      - --rootDir
      - /var/lib/lodestar/validators
      - --server
      - http://consensus:5052
      - --keymanager.enabled
      - "true"
      - --keymanager.address
      - 0.0.0.0
      - --keymanager.port
      - ${KEY_API_PORT:-7500}
      - --graffiti
      - ${GRAFFITI}
      - --logLevel
      - ${LOG_LEVEL}
      - --preset=gnosis
      - --paramsFile=/usr/config.yaml
      - --defaultFeeRecipient
      - ${FEE_RECIPIENT}

  validator-import:
    profiles: ["tools"]
    restart: "unless-stopped"
    image: lodestar:merge
    user: root
    volumes:
      - lsvalidator-data:/var/lib/lodestar/validators
      - ./.eth/validator_keys:/validator_keys
      - /etc/localtime:/etc/localtime:ro
    environment:
      - KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD:-}
      - NETWORK=${NETWORK}
      - CL_NODE=http://consensus:5052
    entrypoint:
      - validator-import.sh
      - node
      - --max-old-space-size=4096
      - /usr/app/node_modules/.bin/lodestar
      - validator
      - import
      - --rootDir
      - /var/lib/lodestar/validators
      - --directory
      - /val_keys
      - --preset=gnosis
      - --paramsFile=/usr/config.yaml
    depends_on:
      - consensus

  validator-exit:
    profiles: ["tools"]
    restart: "no"
    image: lodestar:merge
    user: lsvalidator
    volumes:
      - lsvalidator-data:/var/lib/lodestar/validators
      - /etc/localtime:/etc/localtime:ro
    entrypoint:
      - node
      - --max-old-space-size=4096
      - /usr/app/node_modules/.bin/lodestar
      - validator
      - voluntary-exit
      - --rootDir
      - /var/lib/lodestar/validators
      - --server
      - http://consensus:5052
      -  --logLevel
      - ${LOG_LEVEL}
      - --preset=gnosis
      - --paramsFile=/usr/config.yaml

  validator-keys:
    profiles: ["tools"]
    restart: "no"
    build:
      context: ./vc-utils
    image: vc-utils:local
    user: root
    volumes:
      - lsvalidator-data:/var/lib/lodestar/validators
      - ./.eth/validator_keys:/validator_keys
      - /etc/localtime:/etc/localtime:ro
    environment:
      - LSBUGGED="true"
      - KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD:-}
      - KEY_API_PORT=${KEY_API_PORT:-7500}
    depends_on:
      - validator
    entrypoint:
      - keymanager.sh
      - /var/lib/lodestar/validators/validator-db/api-token.txt
      - validator

volumes:
  lsconsensus-data:
  lsvalidator-data:
  jwtsecret:
