version: "3.4"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  consensus:
    restart: "unless-stopped"
    build:
      context: ./lodestar
      dockerfile: ${LS_DOCKERFILE}
      args:
        - BUILD_TARGET=${LS_SRC_BUILD_TARGET}
        - DOCKER_TAG=${LS_DOCKER_TAG}
    image: lodestar:chiado
    user: lsconsensus
    stop_grace_period: 1m
    volumes:
      - lsconsensus-data:/var/lib/lodestar/consensus
      - /etc/localtime:/etc/localtime:ro
      - jwtsecret:/var/lib/lodestar/consensus/ee-secret
    environment:
      - RAPID_SYNC_URL=${RAPID_SYNC_URL}
      - JWT_SECRET=${JWT_SECRET}
      - OVERRIDE_TTD=${OVERRIDE_TTD}
      - MEV_BOOST=${MEV_BOOST}
    ports:
      - ${CL_P2P_PORT:-9000}:${CL_P2P_PORT:-9000}/tcp
      - ${CL_P2P_PORT:-9000}:${CL_P2P_PORT:-9000}/udp
    <<: *logging
    entrypoint:
      - docker-entrypoint.sh
      - node
      - --max-old-space-size=4096
      - /usr/app/node_modules/.bin/lodestar
      - beacon
      - --rootDir
      - /var/lib/lodestar/consensus
      - --api.rest.enabled
      - "true"
      - --api.rest.host
      - 0.0.0.0
      - --api.rest.port
      - ${CL_REST_PORT:-5052}
      - --network.discv5.bindAddr
      - "/ip4/0.0.0.0/udp/${CL_P2P_PORT:-9000}"
      - --network.localMultiaddrs
      - "/ip4/0.0.0.0/tcp/${CL_P2P_PORT:-9000}"
      - --execution.urls
      - ${EL_NODE}
      - --jwt-secret
      - /var/lib/lodestar/consensus/ee-secret/jwtsecret
      - --network.maxPeers
      - ${CL_MAX_PEER_COUNT:-55}
      - --network.targetPeers
      - ${CL_MIN_PEER_COUNT:-50}
      - --logLevel
      - ${LOG_LEVEL}
      - --preset=gnosis
      - --paramsFile=/usr/config.yaml
      - --genesisStateFile=/usr/genesis.ssz
      - --network.discv5.bootEnrs=enr:-Ly4QIU1Dx10YTI2TwT2K_Q4F1ndzM66qL0UANk0ykTbSHudTuQCdafzduiOMuW5rDbuCB-Ghf4qPDtVC-Qg89PY9TpPh2F0dG5ldHOI__________-EZXRoMpDx7Hf9AgAAb___________gmlkgnY0gmlwhES3U7iJc2VjcDI1NmsxoQNYuaXoECG_MAw_LMa1ST3vVuJUQiaOqHIvTiUhoAPLOYhzeW5jbmV0cweDdGNwgiMog3VkcIIjKA
      - --network.discv5.bootEnrs=enr:-Ly4QHs5ldBMGDK71AE3VoEfNibRdxzVyk1UMnxEWveLaEYfHZJUOJDDmcKCy-tT5yD_V9cIJnB80X7It0N2r9elCg5Nh2F0dG5ldHOI__________-EZXRoMpDx7Hf9AgAAb___________gmlkgnY0gmlwhJ_LJMCJc2VjcDI1NmsxoQMAQwSXGZbvkgrQrRvH4joalSxXOtCdih0OMRtHDtQoU4hzeW5jbmV0cweDdGNwgiMog3VkcIIjKA
      - --network.discv5.bootEnrs=enr:-Ly4QCYxpTU7DYH8Eqx089wdfqVcI1bt-WVg6zfvq4Irl014SMb3ICzbYxHGWdlgBi5OkngJmgMOYgt5fD_x8H9GC1hMh2F0dG5ldHOI__________-EZXRoMpDx7Hf9AgAAb___________gmlkgnY0gmlwhJ_LJ0qJc2VjcDI1NmsxoQNaBCfpdgCXa7eYjghNbmOH8haJPBn15dLhcySi4b1_g4hzeW5jbmV0cw-DdGNwgiMog3VkcIIjKA
      - --network.discv5.bootEnrs=enr:-Ly4QDJlKvfV9xLDeoQVJ0enTOsef3S79SYFrruCHJJI-G7uC4mBjKLsA8KRswdLwif3shvk4BsGIWs62URQcue_SL5Oh2F0dG5ldHOI__________-EZXRoMpDx7Hf9AgAAb___________gmlkgnY0gmlwhJ_fJsSJc2VjcDI1NmsxoQOoU9EazFh7wzXZljrMjUxj9Z-QJENVEPf5dgl07FOsxYhzeW5jbmV0cw-DdGNwgiMog3VkcIIjKA
      - --network.discv5.bootEnrs=enr:-Ly4QEFtAkpJhDYt0vsXrtB-8g1Vm8VK4og08mY6SOG_8y28OecSuKi50LVHloz2by0lfMMvvYI2ZpvWgBwTnE2qrUlTh2F0dG5ldHOI__________-EZXRoMpDx7Hf9AgAAb___________gmlkgnY0gmlwhJ_fM6-Jc2VjcDI1NmsxoQPgk8u6ovWd95LWHGinONa-rS9A_mcX2_L45S0VhQoQ0YhzeW5jbmV0cwuDdGNwgiMog3VkcIIjKA
      - --network.discv5.bootEnrs=enr:-Ly4QLU8f4Wwfc5rlE9bXtb5EEQDFWrHP7_896NSAdTe4pN-BA2-vAWPCfxrz3eN_IGhIy73rAZesDdpplcuMY3jFkVPh2F0dG5ldHOI__________-EZXRoMpDx7Hf9AgAAb___________gmlkgnY0gmlwhLymbsOJc2VjcDI1NmsxoQLgJ3a46Kl1pVLi_kGS6YZXUVzRqB4N1WGU0_V3KeMRZYhzeW5jbmV0cwuDdGNwgiMog3VkcIIjKA
      - --network.discv5.bootEnrs=enr:-Ly4QMDKlbQ_XDxOKRblmbzezV-zoOpHx48B-89HwMD-FC2ZBurkzf0kuVq6vpeEFxorhb63UI2_Lf-SAbwaVzMbdC1Th2F0dG5ldHOI__________-EZXRoMpDx7Hf9AgAAb___________gmlkgnY0gmlwhI5dgFeJc2VjcDI1NmsxoQMHIQkxikidnG1Yp_WOf3ssfvKrl4NxHl0pYP2K-TGyOohzeW5jbmV0cwuDdGNwgiMog3VkcIIjKA
      - --network.discv5.bootEnrs=enr:-Ly4QHt03EegwOf6SIyfaz8OMhrV_Fyso2BnXAZqmQsvnZkHSxMh3uv9N7VbAp0TiNbrx27VjitYXf4GugKucImMIA1Oh2F0dG5ldHOI__________-EZXRoMpDx7Hf9AgAAb___________gmlkgnY0gmlwhJO20mGJc2VjcDI1NmsxoQOsjg1zGLJ8ssPNYdD_Blz7Mb7JYD47uWveEdi-0eV9HIhzeW5jbmV0cw-DdGNwgiMog3VkcIIjKA
      - --network.discv5.bootEnrs=enr:-Ly4QBt28Vj6vdzPCyKDK-e1gUR71CAPirYTjWlKZEFmNcr-JybKd0pvHqv6RF3OqjE8SCsv9z8_3ncZ3LH-0bvTLt5Uh2F0dG5ldHOI__________-EZXRoMpDx7Hf9AgAAb___________gmlkgnY0gmlwhI5dxlqJc2VjcDI1NmsxoQNjIUIWjjHUwjIuSFZ9S_ykD17JVGApixe33OKFDqWq2YhzeW5jbmV0cw-DdGNwgiMog3VkcIIjKA
      - --network.discv5.bootEnrs=enr:-Ly4QDGOHFxjK4cnE16S3ejUxnoGROgbYq-sQkasuC7A__vVHOrIHOIdj2bkRp1ztfu9IO8IF6Ubk1CRF2dlnZn3MPlLh2F0dG5ldHOI__________-EZXRoMpDx7Hf9AgAAb___________gmlkgnY0gmlwhI5dfvaJc2VjcDI1NmsxoQOeYq7S8a1lhmqgkjhhtwBYwgRDahzIpaF58Ij_wj_YrYhzeW5jbmV0cweDdGNwgiMog3VkcIIjKA
      - --network.discv5.bootEnrs=enr:-Ly4QG81SH5A0J3c4RTMd4LVtwM_6BaCDoAa5nLAg0dwcAN_Vf1F4FLDS18jc4j2XaFh4MeVXsw6qT7oSeG1XEoaAHtLh2F0dG5ldHOI__________-EZXRoMpDx7Hf9AgAAb___________gmlkgnY0gmlwhES3BWGJc2VjcDI1NmsxoQIP657MjMdrsoUgZqbYj2ZwlAi-o-5aD_DA6FDoiWN01IhzeW5jbmV0cw6DdGNwgiMog3VkcIIjKA
      - --network.discv5.bootEnrs=enr:-Ly4QHuYCL6w6CPgwSnefC0_vrEi0X8JUgl3UxZes-6ysWvhJJ3OLEMt5tHSLIu8Au0OpV9KVIqGZfT2XESadLrvhIhMh2F0dG5ldHOI__________-EZXRoMpDx7Hf9AgAAb___________gmlkgnY0gmlwhJK-EdKJc2VjcDI1NmsxoQJEqTWbHH0xrPo5GwXC8eNS53nakFtPOoDQL4HyzYN1HIhzeW5jbmV0cw-DdGNwgiMog3VkcIIjKA
      - --network.discv5.bootEnrs=enr:-Ly4QCT7LJp2DGYuWAybZNn_n0hXUvBFssQ10I2zuJNWjJ9dMmaw-zr4a0vhwWcMAqogsAK-aN_7tug8gmJ0yDXQLqRNh2F0dG5ldHOI__________-EZXRoMpDx7Hf9AgAAb___________gmlkgnY0gmlwhIbRyJmJc2VjcDI1NmsxoQNirwCaRwgDJo1dUHX_q1aWkFE8RGslvO8gSaEBDXDYA4hzeW5jbmV0cwuDdGNwgiMog3VkcIIjKA
      - --network.discv5.bootEnrs=enr:-Ly4QLU73apDkT_t-3zWRUm0v_kRemZejnINeZHKI76Rhy7bJrdSLDrsW3w-sbM_k6DgbEQ25ULd6ynH6-mLPdSczxBOh2F0dG5ldHOI__________-EZXRoMpDx7Hf9AgAAb___________gmlkgnY0gmlwhIbRUnWJc2VjcDI1NmsxoQJMNyZCQLM1A39JyzBn2eRPZRiLYKmr0DkjkuM4BeFwLIhzeW5jbmV0cw-DdGNwgiMog3VkcIIjKA
      - --network.discv5.bootEnrs=enr:-Ly4QMZNylaDBmK5VSjx-geQ5e_uTScQoJs_UgEs2RqpXMmaW7sM9yPy2Dx0NsF1av9__fjtJD_MYUY8hpzZ7BZ7JRxRh2F0dG5ldHOI__________-EZXRoMpDx7Hf9AgAAb___________gmlkgnY0gmlwhIbRxsOJc2VjcDI1NmsxoQIq-CuniQWSkHlmRee3_b-hWqacqNOdvIjOe-QY3T1uqYhzeW5jbmV0cw6DdGNwgiMog3VkcIIjKA
      - --network.discv5.bootEnrs=enr:-MK4QKyxiWM_hTzOu8Pqa_xc8m2dFlskgkl3tPYnu06wQX-qM_XjYWtSepaaUEmtcfZttd1PMISxDk23lFm6-anZ9SOGAYKWd6f8h2F0dG5ldHOI__________-EZXRoMpDx7Hf9AgAAb___________gmlkgnY0gmlwhGj4V-GJc2VjcDI1NmsxoQPZv0bCEqyKpOl2AS5MuuPyib2DCnzOgafd5Lx72Lut44hzeW5jbmV0cw-DdGNwgiMog3VkcIIjKA==
      - --network.discv5.bootEnrs=enr:-MK4QO6NkRWirD2D6PJZgDlAWuAJq4jYd2LE2L8Kc_Fys5B5LXMV_C1SFf9-PmRvjd819JRsOJSI2x5kE4MEyOczYu2GAYKWd6bah2F0dG5ldHOI__________-EZXRoMpDx7Hf9AgAAb___________gmlkgnY0gmlwhIbRykyJc2VjcDI1NmsxoQKgpgO0gqduYfHNCr0sd0W0mnJ2DksKwkdD2y0dboXbKYhzeW5jbmV0cw-DdGNwgiMog3VkcIIjKA==
      - --network.discv5.bootEnrs=enr:-MK4QJi8hsv7q1dTMmHvreou23GtZ2_NNXoMWwMIZbc4YUfNKBmc_38_OjWFCdLdgSSlT-rKJoLdcjHgGGAqtBe-WRqGAYKWd6fFh2F0dG5ldHOI__________-EZXRoMpDx7Hf9AgAAb___________gmlkgnY0gmlwhIbRytaJc2VjcDI1NmsxoQOIL4nsJXxUvxQ7y4c3vKWs5oRmd8ECiyOxWzSdo0e454hzeW5jbmV0cw6DdGNwgiMog3VkcIIjKA==
      - --network.discv5.bootEnrs=enr:-MK4QOS80D1piQ76AFGtTrfspszwHWO8u-ntEjAYaPrnZfPfEUaJkFqjuLdvkaFK5-0fjLV9EjQdQPxg-6R8pWJiMomGAYKWd6dDh2F0dG5ldHOI__________-EZXRoMpDx7Hf9AgAAb___________gmlkgnY0gmlwhIbRyoiJc2VjcDI1NmsxoQPZcOGiMqTdrvc3suwqckqnt2CQDx20WFIKNiVd0KlpyIhzeW5jbmV0cweDdGNwgiMog3VkcIIjKA==
      - --network.discv5.bootEnrs=enr:-MK4QHffZZft-LMzH6DsWo7PS0h3RHcGMRFW6lDIT0rvGZCaAdYfNPPQyKQm71-BcBPU744x8Wqdpoxj0HXLFcVXp-KGAYKWJyJNh2F0dG5ldHOI__________-EZXRoMpDx7Hf9AgAAb___________gmlkgnY0gmlwhIbRzo6Jc2VjcDI1NmsxoQJX_8BvdNkVKJmxnQH0G3twoPxDG053KTxfNZB-mylAS4hzeW5jbmV0cw-DdGNwgiMog3VkcIIjKA==
      - --network.discv5.bootEnrs=enr:-Ly4QHt81fiBhU13Bl5fMCpj4N8gBZ8DxcG45DlMDRA4r8LKVGgBDRPrLaFsUwvWdaazFlCKK4WreIin9EjQfnAXi5Ueh2F0dG5ldHOI__________-EZXRoMpDx7Hf9AgAAb___________gmlkgnY0gmlwhI_Gbl2Jc2VjcDI1NmsxoQPWB9x7P_gvlgiWCju3vP1_N56QlNvp9TsMgmpejHVjrohzeW5jbmV0cw-DdGNwgiMog3VkcIIjKA
      - --network.discv5.bootEnrs=enr:-Ly4QC2NH0OgF16Nt0U9tFihaRMuSOgz-regecl4CwLxgNFuDinXA5kx1Kdkk6RsXU9dFw6Q7rBVusCbKCO_G-TAxyY0h2F0dG5ldHOI__________-EZXRoMpDx7Hf9AgAAb___________gmlkgnY0gmlwhJO2wIOJc2VjcDI1NmsxoQLvceYFycNkMFp0dtmypvF1UWS3Lj7r4TMz-yySkWJGFYhzeW5jbmV0cw-DdGNwgiMog3VkcIIjKA
      - --network.discv5.bootEnrs=enr:-Ly4QFM4tKidZqhHTTFwbBHSty61PUF0gptEHx4U4KDcO113URCCGZ90hUIgiIkYr6KXj0B_kXIrV-4C1qvUJYATmiMeh2F0dG5ldHOI__________-EZXRoMpDx7Hf9AgAAb___________gmlkgnY0gmlwhI_0vzCJc2VjcDI1NmsxoQLVdmpEAcINa_pF_TtImigQh_YxhEhD_D6qadqkzjonRYhzeW5jbmV0cweDdGNwgiMog3VkcIIjKA
      - --network.discv5.bootEnrs=enr:-Ly4QAnWMik-0YaOhvdC-Wd50wrJ0Lxf6PIQjj2Ox-dSyHUlUt54FPUjwPK8-cdAOa-NHn6TsMkRfc_FFN8uJn1iRy8xh2F0dG5ldHOI__________-EZXRoMpDx7Hf9AgAAb___________gmlkgnY0gmlwhI_0v4SJc2VjcDI1NmsxoQIkYRn8cx3v3f1DBoqcijVJ33PtZYYdsbOjDX2NynRV3IhzeW5jbmV0cw-DdGNwgiMog3VkcIIjKA
      - --network.discv5.bootEnrs=enr:-Ly4QFEiI77xVFa3nBTOdo2PtclXBF-1723UCixUbrXgFZlfUHvhl0veJzVnx1Pf8Jv-Dsz_6Wq9IQiyeZ_Vh4EHBogbh2F0dG5ldHOI__________-EZXRoMpDx7Hf9AgAAb___________gmlkgnY0gmlwhJO2yCOJc2VjcDI1NmsxoQKJ7eKs25-Cs-AzNom536OOogi-SwHGBYvPp6pX8YTOT4hzeW5jbmV0cw-DdGNwgiMog3VkcIIjKA
      - --network.discv5.bootEnrs=enr:-Ly4QP8fALCluU5OkVBfmZ0kAt3JKvHAC8C55Yjxycsdq-8oXexF2xdLb5AvJiZc4KyX9O_Ao_LkgevTDsJ41prLB60mh2F0dG5ldHOI__________-EZXRoMpDx7Hf9AgAAb___________gmlkgnY0gmlwhI_0v5KJc2VjcDI1NmsxoQLxKRq01HsTuUFl6LBdRqzorl2RNYI6QFv_kya0N4tNrIhzeW5jbmV0cw-DdGNwgiMog3VkcIIjKA
      - --network.discv5.bootEnrs=enr:-Ly4QOOZdRBMWWV77lXNdcruInNpv506UiPBAu8H0lQnVDs1KsZFgYlOWOs7oLp11zEU-a9_2QCdYRewn3Iu36ZdlPMoh2F0dG5ldHOI__________-EZXRoMpDx7Hf9AgAAb___________gmlkgnY0gmlwhI9u0suJc2VjcDI1NmsxoQO636L7J3tvDbqlzlHlvE9OkeqXxN_juM--aSQKepdat4hzeW5jbmV0cwuDdGNwgiMog3VkcIIjKA
      - --network.discv5.bootEnrs=enr:-Ku4QPQ6AA-T2PNyWx_rpHSf0nzCucj1OBvu9LjJL28ZJh_gM0jq_4Ob4txha_9uTmo4DZRzXeVEECUZAIGny2xmUaYuhGV0aDKQ8ex3_QIAAG___________4JpZIJ2NIJpcISPbtLxiXNlY3AyNTZrMaEDEo2QDWfkWCVblbp3mVRGxDo3-tyPqwQZiCglkLHTE_6Ic3luY25ldHMHg3RjcIIjKIN1ZHCCIyq
      - --chain.defaultFeeRecipient
      - ${FEE_RECIPIENT}

  validator:
    restart: "unless-stopped"
    image: lodestar:chiado
    user: lsvalidator
    environment:
      - MEV_BOOST=${MEV_BOOST}
      - DOPPELGANGER=${DOPPELGANGER}
    volumes:
      - lsvalidator-data:/var/lib/lodestar/validators
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - consensus
    <<: *logging
    entrypoint:
      - docker-entrypoint-vc.sh
      - node
      - --max-old-space-size=4096
      - /usr/app/node_modules/.bin/lodestar
      - validator
      - --rootDir
      - /var/lib/lodestar/validators
      - --server
      - http://consensus:5052
      - --keymanager.enabled
      - "true"
      - --keymanager.address
      - 0.0.0.0
      - --keymanager.port
      - ${KEY_API_PORT:-7500}
      - --graffiti
      - ${GRAFFITI}
      - --logLevel
      - ${LOG_LEVEL}
      - --preset=gnosis
      - --paramsFile=/usr/config.yaml
      - --defaultFeeRecipient
      - ${FEE_RECIPIENT}

  validator-import:
    profiles: ["tools"]
    restart: "unless-stopped"
    image: lodestar:chiado
    user: root
    volumes:
      - lsvalidator-data:/var/lib/lodestar/validators
      - ./.eth/validator_keys:/validator_keys
      - /etc/localtime:/etc/localtime:ro
    environment:
      - KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD:-}
      - NETWORK=${NETWORK}
      - CL_NODE=http://consensus:5052
    entrypoint:
      - validator-import.sh
      - node
      - --max-old-space-size=4096
      - /usr/app/node_modules/.bin/lodestar
      - validator
      - import
      - --rootDir
      - /var/lib/lodestar/validators
      - --directory
      - /val_keys
      - --preset=gnosis
      - --paramsFile=/usr/config.yaml
    depends_on:
      - consensus

  validator-exit:
    profiles: ["tools"]
    restart: "no"
    image: lodestar:chiado
    user: lsvalidator
    volumes:
      - lsvalidator-data:/var/lib/lodestar/validators
      - /etc/localtime:/etc/localtime:ro
    entrypoint:
      - node
      - --max-old-space-size=4096
      - /usr/app/node_modules/.bin/lodestar
      - validator
      - voluntary-exit
      - --rootDir
      - /var/lib/lodestar/validators
      - --server
      - http://consensus:5052
      -  --logLevel
      - ${LOG_LEVEL}
      - --preset=gnosis
      - --paramsFile=/usr/config.yaml

  validator-keys:
    profiles: ["tools"]
    restart: "no"
    build:
      context: ./vc-utils
    image: vc-utils:local
    user: root
    volumes:
      - lsvalidator-data:/var/lib/lodestar/validators
      - ./.eth/validator_keys:/validator_keys
      - /etc/localtime:/etc/localtime:ro
    environment:
      - LSBUGGED="true"
      - KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD:-}
      - KEY_API_PORT=${KEY_API_PORT:-7500}
    depends_on:
      - validator
    entrypoint:
      - keymanager.sh
      - /var/lib/lodestar/validators/validator-db/api-token.txt
      - validator

volumes:
  lsconsensus-data:
  lsvalidator-data:
  jwtsecret:
