version: "3"
services:
  beacon:
    restart: "${RESTART}"
    user: ${LOCAL_UID}:${LOCAL_UID}
    build:
      context: ./nimbus
      args:
        - BUILD_TARGET=${NIM_BUILD_TARGET}
        - USER=${NIM_USER}
        - UID=${LOCAL_UID}
        - METRICS=${NIM_METRICS}
    image: nimbus
    volumes:
      - nimbus-data:/var/lib/nimbus
    ports:
      - ${NIM_PORT}:${NIM_PORT}/tcp
      - ${NIM_PORT}:${NIM_PORT}/udp
    entrypoint:
      - /usr/local/bin/beacon_node
      - --data-dir=/var/lib/nimbus
      - --non-interactive
      - --log-file=/var/lib/nimbus/beacon_node.log
      - --tcp-port=${NIM_PORT}
      - --udp-port=${NIM_PORT}
      - --network=${NETWORK}
      - --web3-url=${ETH1_NODE}
      - --graffiti=${GRAFFITI}
      - --log-level=${LOG_LEVEL}
  validator-import:
    restart: "no"
    user: ${LOCAL_UID}:${LOCAL_UID}
    image: nimbus
    build:
      context: ./nimbus
      args:
        - BUILD_TARGET=${NIM_BUILD_TARGET}
        - USER=${NIM_USER}
        - UID=${LOCAL_UID}
        - METRICS=${NIM_METRICS}
    volumes:
      - nimbus-data:/var/lib/nimbus
      - ${DEPCLI_LOCALDIR}/validator_keys:/var/lib/nimbus/validator_keys
    entrypoint:
      - /usr/local/bin/beacon_node
      - --data-dir=/var/lib/nimbus
      - --log-file=/var/lib/nimbus/beacon_node.log
      - --network=${NETWORK}
      - deposits
      - import
      - /var/lib/nimbus/validator_keys
  deposit-cli:
    restart: "no"
    user: ${LOCAL_UID}:${LOCAL_UID}
    build:
      context: ./eth2.0-deposit-cli
      args:
        - BUILD_TARGET=${DEPCLI_SRC_BUILD_TARGET}
        - USER=${DEPCLI_USER}
        - UID=${LOCAL_UID}
    image: eth2.0-deposit-cli
    volumes:
      - ${DEPCLI_LOCALDIR}:/var/lib/depcli-data
    entrypoint:
      - python3
      - /app/eth2deposit/deposit.py
      - new-mnemonic
      - --folder
      - /var/lib/depcli-data
      - --num_validators
      - ${NUMVAL}
      - --chain
      - ${NETWORK}
  deposit-cli-add-recover:
    restart: "no"
    user: ${LOCAL_UID}:${LOCAL_UID}
    build:
      context: ./eth2.0-deposit-cli
      args:
        - BUILD_TARGET=${DEPCLI_SRC_BUILD_TARGET}
        - USER=${DEPCLI_USER}
        - UID=${LOCAL_UID}
    image: eth2.0-deposit-cli
    volumes:
      - ${DEPCLI_LOCALDIR}:/var/lib/depcli-data
    entrypoint:
      - python3
      - /app/eth2deposit/deposit.py
      - existing-mnemonic
      - --folder
      - /var/lib/depcli-data
      - --num_validators
      - ${NUMVAL}
      - --validator_start_index
      - ${VAL_START_INDEX}
      - --chain
      - ${NETWORK}
  eth2:
    image: tianon/true
    restart: "no"
    depends_on:
      - beacon
volumes:
  nimbus-data:
