version: "3.4"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  execution:
    restart: "${RESTART}"
    stop_grace_period: 3m
    stop_signal: SIGINT
    build:
      context: ./nethermind
      dockerfile: ${NM_DOCKERFILE}
      args:
        - BUILD_TARGET=${NM_SRC_BUILD_TARGET}
        - DOCKER_TAG=${NM_DOCKER_TAG}
    image: nethermind:merge
# Root so a chown can happen for the secret, then gosu into nethermind. This can become nethermind again
# after merge
    user: root
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - OVERRIDE_TTD=${OVERRIDE_TTD}
    volumes:
      - nm-eth1-data:/var/lib/nethermind
      - /etc/localtime:/etc/localtime:ro
      - jwtsecret:/var/lib/nethermind/secrets
    ports:
      - ${EL_P2P_PORT:-30303}:${EL_P2P_PORT:-30303}/tcp
      - ${EL_P2P_PORT:-30303}:${EL_P2P_PORT:-30303}/udp
    networks:
      default:
        aliases:
          - eth1
    <<: *logging
    entrypoint:
      - docker-entrypoint.sh
      - dotnet
      - /nethermind/Nethermind.Runner.dll
      - --datadir
      - /var/lib/nethermind
      - --Init.WebSocketsEnabled
      - "true"
      - --Network.DiscoveryPort
      - ${EL_P2P_PORT:-30303}
      - --Network.P2PPort
      - ${EL_P2P_PORT:-30303}
      - --JsonRpc.Enabled
      - "true"
      - --JsonRpc.EnabledModules
      - "Web3,Eth,Subscribe,Net"
      - --JsonRpc.Host
      - 0.0.0.0
      - --JsonRpc.Port
      - ${EL_RPC_PORT:-8545}
      - --JsonRpc.WebSocketsPort
      - ${EL_WS_PORT:-8546}
      - --JsonRpc.AdditionalRpcUrls=http://0.0.0.0:8551|http;wss|engine;eth;net;web3;subscribe
      - --JsonRpc.JwtSecretFile=/var/lib/nethermind/secrets/jwtsecret
      - --Sync.FastSync
      - "true"
      - --Metrics.Enabled
      - "true"
      - --Metrics.ExposePort
      - "6060"
      - --config
      - ${NETWORK}
      - --Pruning.Enabled
      - "true"
      - --Pruning.CacheMb
      - "4096"
      - --Sync.AncientBodiesBarrier
      - "1"
      - --Sync.AncientReceiptsBarrier
      - "1"
      - --log
      - ${LOG_LEVEL}
  eth:
    depends_on:
      - execution
volumes:
  nm-eth1-data:
  jwtsecret:
