version: "3"
services:
  beacon:
    restart: "${RESTART}"
    user: ${LOCAL_UID}:${LOCAL_UID}
    build:
      context: ./prysm
      args:
        - BUILD_TARGET=${PRYSM_BUILD_TARGET}
        - USER=${PRYSM_USER}
        - UID=${LOCAL_UID}
    image: prysm
    volumes:
      - prysmbeacon-data:/var/lib/prysm
    ports:
      - ${PRYSM_PORT}:${PRYSM_PORT}/tcp
      - ${PRYSM_UDP_PORT}:${PRYSM_UDP_PORT}/udp
    expose:
      - 4000
    entrypoint:
      - beacon-chain
      - --datadir
      - /var/lib/prysm/
      - --rpc-host
      - 0.0.0.0
      - --http-web3provider
      - ${ETH1_NODE}
      - --p2p-tcp-port
      - ${PRYSM_PORT}
      - --p2p-udp-port
      - ${PRYSM_UDP_PORT}
      - --verbosity
      - ${LOG_LEVEL}
      - --blst
      - --${TESTNET}
      - --accept-terms-of-use
  validator:
    restart: "${RESTART}"
    user: ${LOCAL_UID}:${LOCAL_UID}
    build:
      context: ./prysm
      args:
        - BUILD_TARGET=${PRYSM_BUILD_TARGET}
        - USER=${PRYSM_USER}
        - UID=${LOCAL_UID}
    image: prysm
    volumes:
      - prysmvalidator-data:/var/lib/prysm
    entrypoint:
      - validator
      - --datadir
      - /var/lib/prysm
      - --wallet-dir
      - /var/lib/prysm/
      - --beacon-rpc-provider
      - beacon:4000
      - --graffiti
      - ${GRAFFITI}
      - --verbosity
      - ${LOG_LEVEL}
      - --blst
      - --${TESTNET}
      - --accept-terms-of-use
      # If you chose not to store the wallet password during import, comment out the two following lines
      - --wallet-password-file
      - /var/lib/prysm/password.txt
    depends_on:
      - beacon
  validator-import:
    restart: "no"
    user: ${LOCAL_UID}:${LOCAL_UID}
    image: prysm
    build:
      context: ./prysm
      args:
        - BUILD_TARGET=${PRYSM_BUILD_TARGET}
        - USER=${PRYSM_USER}
        - UID=${LOCAL_UID}
    volumes:
      - prysmvalidator-data:/var/lib/prysm
      - ${DEPCLI_LOCALDIR}/validator_keys:/var/lib/prysm/validator_keys
    entrypoint: create-prysm-validator-wallet.sh
    command:
      - validator
      - --verbosity
      - ${LOG_LEVEL}
      - --datadir
      - /var/lib/prysm
      - accounts
      - import
      - --wallet-dir
      - /var/lib/prysm/
      - --keys-dir
      - /var/lib/prysm/validator_keys
      - --${TESTNET}
  validator-voluntary-exit:
    restart: "no"
    user: ${LOCAL_UID}:${LOCAL_UID}
    image: prysm
    build:
      context: ./prysm
      args:
        - BUILD_TARGET=${PRYSM_BUILD_TARGET}
        - USER=${PRYSM_USER}
        - UID=${LOCAL_UID}
    volumes:
      - prysmvalidator-data:/var/lib/prysm
    entrypoint:
      - validator
      - --verbosity
      - ${LOG_LEVEL}
      - --datadir
      - /var/lib/prysm
      - accounts
      - voluntary-exit
      - --wallet-dir
      - /var/lib/prysm/
      - --beacon-rpc-provider
      - beacon:4000
      - --wallet-password-file
      - /var/lib/prysm/password.txt
      - --${TESTNET}
  deposit-cli:
    restart: "no"
    user: ${LOCAL_UID}:${LOCAL_UID}
    build:
      context: ./eth2.0-deposit-cli
      args:
        - BUILD_TARGET=${DEPCLI_BUILD_TARGET}
        - USER=${DEPCLI_USER}
        - UID=${LOCAL_UID}
    image: eth2.0-deposit-cli
    volumes:
      - ${DEPCLI_LOCALDIR}:/var/lib/depcli-data
    entrypoint: ${DEPCLI_ENTRYPOINT}
    command:
      - --num_validators
      - ${NUMVAL}
      - --chain
      - ${TESTNET}
  eth2:
    image: tianon/true
    restart: "no"
    depends_on:
      - beacon
      - validator
volumes:
  prysmbeacon-data:
  prysmvalidator-data:
