version: "3.4"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

x-build: &prysm-build
  context: ./prysm
  dockerfile: ${PRYSM_DOCKERFILE}
  args:
    - BUILD_TARGET=${PRYSM_SRC_BUILD_TARGET}
    - DOCKER_TAG=${PRYSM_DOCKER_TAG}

services:
  consensus:
    restart: "${RESTART}"
    build:
      target: consensus
      <<: *prysm-build
    image: prysm-consensus:merge
    user: prysmconsensus
    stop_grace_period: 1m
    volumes:
      - prysmbeacon-data:/var/lib/prysm
      - /etc/localtime:/etc/localtime:ro
      - jwtsecret:/var/lib/prysm/secrets
    environment:
      - RAPID_SYNC_URL=${RAPID_SYNC_URL}
      - JWT_SECRET=${JWT_SECRET}
      - OVERRIDE_TTD=${OVERRIDE_TTD}
    ports:
      - ${PRYSM_PORT}:${PRYSM_PORT}/tcp
      - ${PRYSM_UDP_PORT}:${PRYSM_UDP_PORT}/udp
    networks:
      default:
        aliases:
          - eth2
    <<: *logging
    entrypoint:
      - docker-entrypoint.sh
      - beacon-chain
      - --datadir
      - /var/lib/prysm/
      - --rpc-host
      - 0.0.0.0
      - --grpc-gateway-host
      - 0.0.0.0
      - --grpc-gateway-port
      - "5052"
      - --http-web3provider
      - ${EL_NODE}
      - --jwt-secret
      - /var/lib/prysm/secrets/jwtsecret
      - --p2p-tcp-port
      - ${PRYSM_PORT}
      - --p2p-udp-port
      - ${PRYSM_UDP_PORT}
      - --p2p-max-peers
      - ${CL_MAX_PEER_COUNT:-45}
      - --verbosity
      - ${LOG_LEVEL}
      - --${NETWORK}
      - --accept-terms-of-use
      - --monitoring-host
      - 0.0.0.0
      - --monitoring-port
      - "8008"
      - --suggested-fee-recipient
      - ${FEE_RECIPIENT}
  validator:
    restart: "${RESTART}"
    build:
      target: validator
      <<: *prysm-build
    image: prysm-validator:merge
    user: prysmvalidator
    volumes:
      - prysmvalidator-data:/var/lib/prysm
      - /etc/localtime:/etc/localtime:ro
    <<: *logging
    entrypoint:
      - validator
      - --datadir
      - /var/lib/prysm
      - --wallet-dir
      - /var/lib/prysm/
      - --beacon-rpc-provider
      - consensus:4000
      - --graffiti
      - ${GRAFFITI}
      - --verbosity
      - ${LOG_LEVEL}
      - --${NETWORK}
      - --accept-terms-of-use
      - --monitoring-host
      - 0.0.0.0
      - --monitoring-port
      - "8009"
      - --web
      - --grpc-gateway-host
      - 0.0.0.0
      - --grpc-gateway-port
      - ${KEY_API_PORT:-7500}
      - --grpc-gateway-corsdomain=*
      - --beacon-rpc-gateway-provider
      - consensus:5052
      - --suggested-fee-recipient
      - ${FEE_RECIPIENT}
      # If you chose not to store the wallet password during import, comment out the two following lines
      - --wallet-password-file
      - /var/lib/prysm/password.txt
    depends_on:
      - consensus
    labels:
      - traefik.enable=true
      - traefik.http.routers.prysm.entrypoints=web,websecure
      - traefik.http.routers.prysm.rule=Host(`${PRYSM_HOST}.${DOMAIN}`)
      - traefik.http.routers.prysm.tls.certresolver=letsencrypt
      - traefik.http.services.prysm.loadbalancer.server.port=${KEY_API_PORT:-7500}
  create-wallet:
    profiles: ["tools"]
    restart: "no"
    image: prysm-validator:merge
    user: prysmvalidator
    environment:
      - NETWORK=${NETWORK}
    volumes:
      - prysmvalidator-data:/var/lib/prysm
      - /etc/localtime:/etc/localtime:ro
    entrypoint: create-wallet.sh
  get-keyapi-token:
    profiles: ["tools"]
    restart: "no"
    image: alpine:latest
    user: "10000"
    volumes:
      - prysmvalidator-data:/var/lib/prysm
      - /etc/localtime:/etc/localtime:ro
    <<: *logging
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        sed -n 2p /var/lib/prysm/auth-token
  validator-list:
    profiles: ["tools"]
    restart: "no"
    user: prysmvalidator
    image: prysm-validator:merge
    volumes:
      - prysmvalidator-data:/var/lib/prysm
      - /etc/localtime:/etc/localtime:ro
    entrypoint:
      - validator
      - --datadir
      - /var/lib/prysm
      - --verbosity
      - ${LOG_LEVEL}
      - accounts
      - list
      - --wallet-dir=/var/lib/prysm/
      - --${NETWORK}
      # If you chose not to store the wallet password during import, comment out the following line
      - --wallet-password-file=/var/lib/prysm/password.txt
  validator-import:
    profiles: ["tools"]
    restart: "no"
    image: prysm-validator:merge
    user: root
    volumes:
      - prysmvalidator-data:/var/lib/prysm
      - ./.eth/validator_keys:/validator_keys
      - /etc/localtime:/etc/localtime:ro
    environment:
      - KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD:-}
      - WALLET_PASSWORD=${WALLET_PASSWORD:-}
    entrypoint:
      - validator-import.sh
      - validator
      - --verbosity
      - ${LOG_LEVEL}
      - --datadir
      - /var/lib/prysm
      - accounts
      - import
      - --wallet-dir=/var/lib/prysm/
      - --keys-dir=/val_keys
      - --${NETWORK}
  validator-exit:
    profiles: ["tools"]
    restart: "no"
    user: prysmvalidator
    image: prysm-validator:merge
    volumes:
      - prysmvalidator-data:/var/lib/prysm
      - /etc/localtime:/etc/localtime:ro
    entrypoint:
      - validator
      - --verbosity
      - ${LOG_LEVEL}
      - --datadir
      - /var/lib/prysm
      - accounts
      - voluntary-exit
      - --wallet-dir=/var/lib/prysm/
      - --beacon-rpc-provider=consensus:4000
      - --wallet-password-file=/var/lib/prysm/password.txt
      - --${NETWORK}
    depends_on:
      - consensus
volumes:
  prysmbeacon-data:
  prysmvalidator-data:
  jwtsecret:
