version: "3.4"
services:
  beacon:
    restart: "${RESTART}"
    build:
      context: ./teku
      args:
        - BUILD_TARGET=${TEKU_SRC_BUILD_TARGET}
        - DOCKER_TAG=${TEKU_DOCKER_TAG}
      dockerfile: ${TEKU_DOCKERFILE}
    image: teku:local
    volumes:
      - teku-data:/var/lib/teku
    environment:
      - JAVA_OPTS=-XX:SoftMaxHeapSize=2g
    ports:
      - ${TEKU_PORT}:${TEKU_PORT}/tcp
      - ${TEKU_PORT}:${TEKU_PORT}/udp
    entrypoint:
      - docker-entrypoint.sh
      - /opt/teku/bin/teku
      - --data-path=/var/lib/teku
      - --log-destination=CONSOLE
      - --network=${NETWORK}
      - --eth1-endpoints=${ETH1_NODE}
      - --p2p-port=${TEKU_PORT}
      - --p2p-peer-upper-bound=${TEKU_PEER_COUNT}
      - --validators-keystore-locking-enabled=true
      - --validator-keys=/var/lib/teku/validator-keys:/var/lib/teku/validator-passwords
      - --validators-graffiti=${GRAFFITI}
      - --logging=${LOG_LEVEL}
      - --rest-api-host-allowlist=*
      - --rest-api-enabled=true
    command: ${TEKU_RAPID_SYNC}
  validator-import:
    restart: "no"
    image: teku:local
    volumes:
      - teku-data:/var/lib/teku
      - ${DEPCLI_LOCALDIR}/validator_keys:/validator_keys
    entrypoint: validator-import.sh
  validator-exit:
    restart: "no"
    image: teku:local
    user: teku
    volumes:
      - teku-data:/var/lib/teku
    entrypoint:
      - /opt/teku/bin/teku 
      - voluntary-exit
      - --beacon-node-api-endpoint=http://beacon:5051
      - --validator-keys=/var/lib/teku/validator-keys:/var/lib/teku/validator-passwords
  eth2:
    image: tianon/true
    restart: "no"
    depends_on:
      - beacon
volumes:
  teku-data:
