name: docker-compose-actions-workflow

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test default.env
        run: |
          cp default.env .env
          docker-compose up -d eth
